version: "3"
services:
  postgres:
    container_name: trybe_db
    image: postgres:12.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_DB=root
      - POSTGRES_PASSWORD=pass
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
  service:
    container_name: server
    build:
      context: ./service
      dockerfile: Dockerfile.dev  # on move to prod, update this
    volumes:
      - /app/node_modules
      - ./service/config:/app/config
      - ./service/src:/app/src
      - ./service/test:/app/test
    ports:
      - "3000:3000"
  ui:
    container_name: ui
    build:
      context: ./ui
      dockerfile: Dockerfile.dev  # on move to prod, update this
    volumes:
      - /app/node_modules
      - ./ui/src:/app/src
      - ./ui/public:/app/public
      - ./ui/.env:/app/.env:ro
    ports:
      - "8080:8080"
